"""create orders schema tables

Revision ID: 773898bfb7d6
Revises: 2c4b07454632
Create Date: 2026-07-14 23:42:48.542861

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '773898bfb7d6'
down_revision: Union[str, Sequence[str], None] = '2c4b07454632'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('idempotency_key', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key'),
    schema='orders'
    )
    op.create_index(op.f('ix_orders_orders_user_id'), 'orders', ['user_id'], unique=False, schema='orders')
    op.create_table('order_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('book_id', sa.UUID(), nullable=False),
    sa.Column('title_snapshot', sa.String(length=300), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('line_total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.orders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='orders'
    )
    op.create_index(op.f('ix_orders_order_items_order_id'), 'order_items', ['order_id'], unique=False, schema='orders')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orders_order_items_order_id'), table_name='order_items', schema='orders')
    op.drop_table('order_items', schema='orders')
    op.drop_index(op.f('ix_orders_orders_user_id'), table_name='orders', schema='orders')
    op.drop_table('orders', schema='orders')
    # ### end Alembic commands ###
